Repository AY2425S1-CS2103T-W13-2/tp, pull requests merged in 2024-11, with the labels that each got.

#158 Minor bugs in uml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/FindArchitectureSeqDiagram.puml
  docs/diagrams/style.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/FindArchitectureSeqDiagram.png
Labels: alpha-bug

#148 Fix focus issue with right pane upon adding new contact
  src/main/java/careconnect/logic/commands/AddCommand.java
  src/test/java/careconnect/logic/commands/AddCommandIntegrationTest.java
  src/test/java/careconnect/logic/commands/AddCommandTest.java
Labels: alpha-bug

#149 Fix stacked commands
  src/main/java/careconnect/logic/LogicManager.java
  src/main/java/careconnect/logic/Messages.java
  src/main/java/careconnect/logic/commands/AddLogCommand.java
  src/main/java/careconnect/logic/commands/ClearCommand.java
  src/main/java/careconnect/logic/commands/Command.java
  src/main/java/careconnect/logic/commands/ConfirmationNoCommand.java
  src/main/java/careconnect/logic/commands/ConfirmationYesCommand.java
  src/main/java/careconnect/logic/commands/DeleteCommand.java
  src/main/java/careconnect/logic/commands/DeleteLogCommand.java
  src/main/java/careconnect/logic/commands/EditCommand.java
  src/main/java/careconnect/logic/commands/SetAppointmentCommand.java
  src/main/java/careconnect/logic/commands/TagCommand.java
  src/main/java/careconnect/logic/commands/UntagCommand.java
  src/main/java/careconnect/logic/commands/ViewCommand.java
  src/test/java/careconnect/logic/LogicManagerTest.java
  src/test/java/careconnect/logic/commands/ClearCommandTest.java
  src/test/java/careconnect/logic/commands/DeleteCommandTest.java
Labels: alpha-bug

#164 Improve error reporting in actions pipeline
  .github/workflows/gradle.yml
Labels: type.Enhancement

#167 Person list case
  docs/UserGuide.md
  src/main/java/careconnect/model/person/UniquePersonList.java
Labels: alpha-bug

#166 Ug updates
  docs/UserGuide.md
Labels: alpha-bug

#174 Remove seedu reference in DG
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Testing.md
Labels: alpha-bug

#165 fix: Check for log date being in the past
  src/main/java/careconnect/logic/Messages.java
  src/main/java/careconnect/logic/parser/AddLogCommandParser.java
  src/test/java/careconnect/logic/commands/CommandTestUtil.java
  src/test/java/careconnect/logic/parser/AddLogCommandParserTest.java
Labels: alpha-bug

#172 feat: switch focus on shift + tab key press
  src/main/java/careconnect/ui/CommandBox.java
  src/main/java/careconnect/ui/LogListPanel.java
  src/main/java/careconnect/ui/MainWindow.java
  src/main/java/careconnect/ui/PersonCard.java
  src/main/java/careconnect/ui/PersonDetailCard.java
  src/main/java/careconnect/ui/PersonListPanel.java
  src/main/java/careconnect/ui/ShiftTabFocusable.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/theme.css
Labels: alpha-bug

#175 Make toString methods consistent
  src/main/java/careconnect/logic/commands/AddLogCommand.java
  src/main/java/careconnect/logic/commands/DeleteLogCommand.java
  src/test/java/careconnect/logic/commands/AddLogCommandTest.java
  src/test/java/careconnect/logic/commands/DeleteLogCommandTest.java
Labels: alpha-bug

#176 Minor frontend cleanups
  src/main/java/careconnect/ui/UiManager.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/LogCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetailCard.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/theme.css
Labels: type.Enhancement

#177 Fix small issues
  docs/UserGuide.md
  docs/images/validCommand.png
  src/main/java/careconnect/logic/Logic.java
  src/main/java/careconnect/logic/LogicManager.java
  src/main/java/careconnect/logic/commands/SetAppointmentCommand.java
  src/main/java/careconnect/ui/CommandBox.java
  src/main/java/careconnect/ui/MainWindow.java
  src/main/java/careconnect/ui/PersonCard.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/theme.css
  src/test/java/careconnect/logic/LogicManagerTest.java
Labels: alpha-bug

#267 fix: amend find command error message
  src/main/java/careconnect/logic/commands/FindCommand.java
  src/main/java/careconnect/logic/parser/FindCommandParser.java
Labels: type.Bug

#269 docs: update user stories in DG
  docs/DeveloperGuide.md
Labels: documentation

#272 docs: added disclaimer about the usage of `AddressBook` in DG
  docs/DeveloperGuide.md
Labels: documentation

#275 docs: add autocomplete implementation to dg
  docs/DeveloperGuide.md
Labels: documentation

#276 docs: formatting in DG for notes on use of AddressBook
  docs/DeveloperGuide.md
Labels: documentation
