Repository AY2425S1-CS2103T-W13-2/tp, pull requests merged in 2024-10, with the labels that each got.

#17 Add Celes' photo
  docs/images/celeschai.png
Labels: type.Chore

#21 Update AboutUs
  docs/AboutUs.md
  docs/team/celeschai.md
Labels: type.Chore

#26 Add Suhail Details in About Us
  docs/AboutUs.md
  docs/team/johndoe.md
  docs/team/suhailloya.md
Labels: type.Chore

#36 Update Build Status Action Badge for Github Workflows
  README.md
Labels: type.Chore

#28 Update README and UI mockup
  README.md
  docs/images/Ui.png
Labels: type.Chore

#40 Update Site Wide Setting
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: type.Chore

#38 Update DG with target user & value prop
  docs/DeveloperGuide.md
Labels: type.Chore

#34 Add update operation to DG user stories
  docs/DeveloperGuide.md
Labels: type.Chore

#60 Update use cases in DG
  docs/DeveloperGuide.md
Labels: type.Chore

#62 Add Acknowledgements in ReadMe and Developer Guide
  README.md
  docs/DeveloperGuide.md
Labels: type.Chore

#65 Update Use Case in DG
  docs/DeveloperGuide.md
Labels: type.Chore

#72 Allow partial string matching in search
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
Labels: type.Enhancement

#76 Sort contacts lexicographically
  build.gradle
  src/main/java/careconnect/model/person/UniquePersonList.java
  src/test/java/careconnect/model/person/UniquePersonListTest.java
Labels: type.Enhancement

#80 Customise Ui for CareConnect
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/findBensonCarlResult.png
  docs/images/helpMessage.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
Labels: priority.Medium

#93 Autocomplete for commands
  docs/UserGuide.md
  src/main/java/careconnect/logic/Logic.java
  src/main/java/careconnect/logic/LogicManager.java
  src/main/java/careconnect/logic/Messages.java
  src/main/java/careconnect/logic/autocompleter/Autocompleter.java
  src/main/java/careconnect/logic/autocompleter/exceptions/AutocompleteException.java
  src/main/java/careconnect/ui/CommandBox.java
  src/main/java/careconnect/ui/MainWindow.java
  src/test/java/careconnect/logic/LogicManagerTest.java
  src/test/java/careconnect/logic/autocompleter/AutocompleterTest.java
Labels: type.Enhancement

#95 Update Version in MainApp.java to V1.3.0
  src/main/java/careconnect/MainApp.java
Labels: type.Chore

#97 Allow extra whitespace in command
  src/main/java/careconnect/logic/LogicManager.java
  src/test/java/careconnect/logic/LogicManagerTest.java
Labels: type.Bug

#101 Add Missing Tests for Autocomplete
  src/main/java/careconnect/logic/autocompleter/exceptions/AutocompleteException.java
  src/test/java/careconnect/logic/autocompleter/AutocompleterTest.java
Labels: severity.Low

#108 Enable java assertions in build.gradle
  build.gradle
Labels: type.Enhancement

#112 Tag find
  src/main/java/careconnect/commons/util/StringUtil.java
  src/main/java/careconnect/logic/LogicManager.java
  src/main/java/careconnect/logic/commands/FindCommand.java
  src/main/java/careconnect/logic/parser/FindCommandParser.java
  src/main/java/careconnect/model/person/NameAndAddressAndTagsContainsKeywordsPredicate.java
  src/main/java/careconnect/model/person/NameAndAddressContainsKeywordPredicate.java
  src/test/java/careconnect/logic/commands/FindCommandTest.java
  src/test/java/careconnect/logic/parser/AddressBookParserTest.java
  src/test/java/careconnect/logic/parser/FindCommandParserTest.java
Labels: priority.Medium

#122 Update Version in MainApp.java to V1.4.0
  src/main/java/careconnect/MainApp.java
Labels: type.Chore

#120 Add confirmation workflow for commands
  src/main/java/careconnect/logic/LogicManager.java
  src/main/java/careconnect/logic/Messages.java
  src/main/java/careconnect/logic/commands/ClearCommand.java
  src/main/java/careconnect/logic/commands/Command.java
  src/main/java/careconnect/logic/commands/CommandStack.java
  src/main/java/careconnect/logic/commands/ConfirmationNoCommand.java
  src/main/java/careconnect/logic/commands/ConfirmationYesCommand.java
  src/main/java/careconnect/logic/commands/DeleteCommand.java
  src/main/java/careconnect/logic/commands/DeleteLogCommand.java
  src/main/java/careconnect/logic/parser/AddressBookParser.java
  src/test/java/careconnect/logic/commands/ClearCommandTest.java
  src/test/java/careconnect/logic/commands/DeleteCommandTest.java
Labels: type.Enhancement

#124 Update sequence diagram for delete command
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
Labels: type.Chore

#150 Home Address gets truncated if it's too long
  src/main/java/careconnect/ui/PersonDetailCard.java
  src/main/resources/view/PersonDetailCard.fxml
Labels: alpha-bug
